# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\manue\OneDrive\Documents\UNI\Pensamiento_visual\grupo6\Juego\frontend\uis\ventana_inicio.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(721, 626)
        Form.setMinimumSize(QtCore.QSize(721, 626))
        Form.setMaximumSize(QtCore.QSize(721, 626))
        Form.setStyleSheet("background-color: rgb(210, 215, 223);\n"
"font: 28pt \"MS Shell Dlg 2\";")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 10, 701, 601))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 460, 659, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.buttons = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.buttons.setContentsMargins(0, 0, 0, 0)
        self.buttons.setObjectName("buttons")
        self.start = QtWidgets.QPushButton(self.layoutWidget)
        self.start.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.start.setAutoExclusive(False)
        self.start.setFlat(False)
        self.start.setObjectName("start")
        self.buttons.addWidget(self.start)
        self.exit = QtWidgets.QPushButton(self.layoutWidget)
        self.exit.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.exit.setObjectName("exit")
        self.buttons.addWidget(self.exit)
        self.logo = QtWidgets.QLabel(self.frame)
        self.logo.setGeometry(QtCore.QRect(160, 70, 351, 331))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("c:\\Users\\manue\\OneDrive\\Documents\\UNI\\Pensamiento_visual\\grupo6\\Juego\\frontend\\uis\\../../../../../../../../Downloads/552be892e7d94d549e65871650a686b2 (1).png"))
        self.logo.setScaledContents(True)
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.start.setText(_translate("Form", "Comenzar"))
        self.exit.setText(_translate("Form", "Salir"))
